name: ultradesign
favicon: null
layout_spectrum: 0.80445
typography_spectrum: 0.57942
title: Ultra Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#46474c'
    - '#eae1d0'
    - '#7b7b7b'
    - '#9b9b9b'
    - '#a5cd3f'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
